import {
    CalendarOutline,
    CaretRightOutline,
    CheckCircleTwoTone,
    FormOutline,
    LinkOutline,
    LoadingOutline,
    LoginOutline,
    LogoutOutline,
    MenuFoldOutline,
    MenuUnfoldOutline,
    PlusOutline,
    SettingOutline,
    StarOutline,
    TeamOutline,
    UserOutline,
} from "@ant-design/icons-angular/icons";

export const icons = [
    CalendarOutline,
    CaretRightOutline,
    CheckCircleTwoTone,
    FormOutline,
    LinkOutline,
    LoadingOutline,
    LoginOutline,
    LogoutOutline,
    MenuFoldOutline,
    MenuUnfoldOutline,
    PlusOutline,
    SettingOutline,
    StarOutline,
    TeamOutline,
    UserOutline,
];
